### ISSUE TITLE
Allow override of CoreDataManager.saveDataStore

### ISSUE THREAD

**Issue by dmorrow** [contentful/contentful-persistence.objc#14]
Currently, the method `-(void)resolveRelationships` is defined as a private method, not in CoreDataManager.h.

This is a problem is we want to override `saveDataStore` in order to provide better error handling.  In this case, I am calling `rollback` on the context to remove changes that wouldn't save, rather than crashing.

In Swift:

    self.resolveRelationships()
        
    if let context = self.managedObjectContext where context.hasChanges {
        do {
            try context.save()
        } catch let error as NSError {
            print("Unresolved error \(error), \(error.userInfo)")
            context.rollback()
        }
    }

**Comment by neonichu** [comment]
I think this would also be suite well for a delegate for allowing consumers of the API to provide custom error handling. Similar to #13

**Comment by dmorrow** [comment]
Agreed

**Comment by neonichu** [comment]
Fixed by 2c8fe0ed22e98b1db0c8ce266207ca718854430d
