### ISSUE TITLE
[Version 0.5.0] Retain cycle occurs at automatic deletion of incompatible data model

### ISSUE THREAD

**Issue by M2Bas** [contentful/contentful-persistence.objc#17]
The change described here:
https://github.com/contentful/contentful-persistence.objc/commit/4327f063156d189abeb1389a166bf1c14f3ba700

Causes a retain cycle if you have a newer version of your model, and you don't respond to the custom migration delegate selector.
`@selector(dataManager:handleMigrationWithMetadata:)`

The function deleteAll calls the managedObjectContext:

`- (NSManagedObjectContext *)managedObjectContext
{
    if (_managedObjectContext != nil) {
        return _managedObjectContext;
    }
    
    NSPersistentStoreCoordinator *coordinator = [self persistentStoreCoordinator];`

Which as you can see calls the persistentStoreCoordinator again, causing the retain cycle to happen.

Result:
If didn't respond to the custom migration, the App will crash

**Comment by M2Bas** [comment]
@neonichu would you be able to share a timeframe on when this bug could be resolved?
We have an App release lined up that is dependent on this improvement, updating our model by quite a bit.

**Comment by neonichu** [comment]
Sorry for the delay in fixing this, version 0.5.1 has just been released.
