### ISSUE TITLE
How to handle links to unpublished content?

### ISSUE THREAD

**Issue by neonichu** [contentful/contentful-persistence.objc#18]
Any dead links are not ending up in the local persistence store when using this library. If we now consider the case where link targets are synced after the link sources and links themselves have, those links would not be available locally, unless the link source also changes, because the links are a property of the source. This goes against the expectation of users that the locale persistence store reflects the state on Contentful and is also hard to debug.

Current workaround is republishing link sources when link targets get published after the fact.

**Comment by loudmouth** [comment]
Closing as project is now deprecated
