### ISSUE TITLE
Version 0.7.0 missing tag

### ISSUE THREAD

**Issue by dmorrow** [contentful/contentful-persistence.objc#19]
The podspec references version 0.7.0, but the latest tag is 0.6.0.
This is preventing me from updating ContentfulDeliveryAPI as well

**Comment by loudmouth** [comment]
Thanks for bringing this to my attention. I'll tag and push the Podspec right away.

**Comment by loudmouth** [comment]
[`v0.7.0`](https://github.com/contentful/contentful-persistence.objc/releases/tag/0.7.0) has been tagged and the Podspec has been pushed to [Contentful's specs repo](https://github.com/contentful/CocoaPodsSpecs)

Please let me know if everything is working as expected.

**Comment by loudmouth** [comment]
Closing this and assuming the lack of response means everything is working ok.
