### ISSUE TITLE
Pod is not available in cocoapods repo

### ISSUE THREAD

**Issue by maxkomarychev** [contentful/contentful-persistence.objc#20]
Hi,

I've noticed that this pod is not available in the master repo for cocoapods. It is a bit confusing since it's counterpart - ContentfulDeliveryAPI is available through master repo of cocoapods.

Another thing I've noticed when added `source` declaration - I'm seeing a warning of duplicated specs when installing pods:

```
[!] Found multiple specifications for `Result (0.6-beta.1)`:
- HOMEFOLDER/.cocoapods/repos/contentful/Result/0.6-beta.1/Result.podspec.json
- HOMEFOLDER/.cocoapods/repos/master/Specs/8/e/e/Result/0.6-beta.1/Result.podspec.json
```

I've checked files and the spec you have in https://github.com/contentful/CocoaPodsSpecs/tree/master/Result/0.6-beta.1 is identical to what is published in master repo.

**Comment by loudmouth** [comment]
Hey @maxkomarychev,

Thanks for bringing this to my attention. I'll get this published to the main cocoapods repo ASAP.

**Comment by loudmouth** [comment]
Hey @maxkomarychev, a quick update—I will need to update the Realm dependency to make the Pod ready for publishing. This shouldn't take long, but may cause a delay of a day or 2 if there are unforeseeable roadblocks.

**Comment by loudmouth** [comment]
Hi @maxkomarychev 

This repo is now published to Cocoapods, so it should no longer be necessary to add an extra line to your Podfile to source an additional specs repo.

The package name has changed and to add this repo to your project you will now just need the following in your Podfile:
```
pod "ContentfulPersistenceObjC"
```

A necessary step to publishing was updating Realm from v0.98.0 to v2.5.0. If you use Realm, please let me know if you encounter any regressions.
