### ISSUE TITLE
Provide helper for location values

### ISSUE THREAD

**Issue by neonichu** [contentful/contentful-persistence.objc#5]
The CDA SDK has a helper for these: http://cocoadocs.org/docsets/ContentfulDeliveryAPI/1.7.4/Classes/CDAEntry.html#//api/name/CLLocationCoordinate2DFromFieldWithIdentifier:

Currently needs to be done manually if using persistence:

``` objectivec
id value = …; // The property value from Core Data
CLLocationCoordinate2D location = { 0.0, 0.0 };
 [value getBytes:&location length:sizeof(location)];
```

**Comment by loudmouth** [comment]
Closing as project is now deprecated
