### ISSUE TITLE
Support persisting multiple locales

### ISSUE THREAD

**Issue by neonichu** [contentful/contentful-persistence.objc#6]
We could approach it the same way as contentful/vault#78

**Comment by marthinfreij** [comment]
I'm currently investigating Contentful for a content driven app localized into seven languages. All languages must be available offline and user should be able to change language independently from the device language settings.

Maybe one could define a Core Data model as Entity with a to-many relationship to EntityLocalized. Localizable properties goes into EntityLocalized and the others into Entity. Entity could expose localized properties via computed properties based on the selected language.
