### ISSUE TITLE
Delete no longer existing relationships when syncing

### ISSUE THREAD

**Issue by neonichu** [contentful/contentful-persistence.objc#7]
Currently, relationships are only created and never deleted.

**Comment by Conrad-m-wise** [comment]
Any update on this bug. I am seeing some synchronisation issues where old data is not being removed.

**Comment by neonichu** [comment]
@Conrad-m-wise sorry, we are working on this for the next release, no concrete ETA, yet, though.

**Comment by Conrad-m-wise** [comment]
Cool! good to know i will check it out with the 0.3.0 release thanks
