### ISSUE TITLE
Enable overriding CoreData stack in subclasses

### ISSUE THREAD

**Issue by Conrad-m-wise** [contentful/contentful-persistence.objc#8]
Hi,

I am using the Contentful-persistence lib in my swift project and all is well. I want to change the cora data stack implementation of the CoreDataManager class to include light-wight-migration and some better error handling and managed Object Context creation. My Project is a pure swift project and i am not sure how best to extended/modify the implementation of the CoreDataManager class within my project.  The core data stack properties of the CoreDataManager class are internal to the class implementation so overriding them in a subclass is difficult (right?). I am a bit stuck here on how best to move forward. I don't want to re-write it in swift because i am not aware of all the implementation detail choices and might brake the working implementation. I am only interested, at the moment to provide my own core data stack for the CoreDataManager.

**Comment by neonichu** [comment]
So essentially, you would want to provide your own implementations of `-managedObjectContext` and `-persistentStoreCoordinator`, right?

**Comment by Conrad-m-wise** [comment]
Correct.

**Comment by neonichu** [comment]
Since we're dealing with an ObjC class here, you can just override the property in your subclass, using something like this:

```swift
import ContentfulPersistence

class OwnCoreDataManager: CoreDataManager {
    override init?(client: CDAClient) {
        super.init(client: client, dataModelName: "ContentfulModel")
    }

    func persistentStoreCoordinator() -> NSPersistentStoreCoordinator {
        let model = self.valueForKey("managedObjectModel") as! NSManagedObjectModel
        let coordinator = NSPersistentStoreCoordinator(managedObjectModel: model)
        _ = try? coordinator.addPersistentStoreWithType(NSInMemoryStoreType, configuration: nil, URL: nil, options: nil)
        return coordinator
    }
}
```

This is obviously a bit brittle, as you won't get any help from the compiler when `CoreDataManager` changes, so I'll add the relevant properties to the interface in an upcoming versions.

**Comment by Conrad-m-wise** [comment]
Ok, Yeah i was hoping not to have to do something like this but it will definitely work. I will think it over and decide if i will implement this solution or wait for the update. Thanks again for the support

**Comment by dmorrow** [comment]
At very least, move `@property (nonatomic) NSManagedObjectModel *managedObjectModel;` and `@property (nonatomic) NSPersistentStoreCoordinator *persistentStoreCoordinator;` to CoreDataManager.h.  This enables better subclassing without having to resort to KVC.

**Comment by dmorrow** [comment]
@Conrad-m-wise You can expose these private methods and properties by adding them to your BridgingHeader.h file.  This is what we've done.  Still brittle in the case of changes in the source, but less so re: typos and type checking from the Swift compiler.

    @interface CoreDataManager(Private)
        @property (nonatomic) NSManagedObjectModel *managedObjectModel;
        @property (nonatomic) NSPersistentStoreCoordinator *persistentStoreCoordinator;
    @end
